language: c
compiler: gcc
sudo: false

dist: bionic
addons:
  apt:
    update: true
    packages:
      - cmake-data
      - cmake
      - lcov
      - valgrind
      - mingw-w64

script:
  - cd build/
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make
  - cd ../profiling
  - ./memcheck.sh 42
  - ./memcheck.sh 0x42
  - ./memcheck.sh 42h
  - ./memcheck.sh 101010b
  - cd ../test/functional/
  - ./functional_test.sh
  - cd ../../coverage/
  - ./coverage.sh
  - cd ..
  - cd build/
  - i686-w64-mingw32-gcc -s -D__USE_MINGW_ANSI_STDIO -Wall -O3 -o numconvert.exe ../src/main.c

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - numconvert
    - numconvert.exe
  skip_cleanup: true
  on:
    tags: true
