language: c
compiler: gcc
sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      - lcov

script:
  - cd build/
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make
  - cd ../test/functional/
  - ./functional_test.sh
  - cd ../../coverage/
  - ./coverage.sh

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: numconvert
  skip_cleanup: true
  on:
    tags: true
