[package]
name = "src_rust"
version = "0.1.0"
authors = ["baskapteijn <baskapteijn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
